// Automated Transaction Engine for Gold Smith Accounting
// Handles automatic journal entries for sales, purchases, payments, and inventory adjustments

export class AutomatedTransactionEngine {
  constructor(companyId) {
    this.companyId = companyId;
  }

  /**
   * Create automated journal entry for sales transaction
   * @param {Object} saleData - Sale transaction data
   * @returns {Object} Journal entry data
   */
  createSaleEntry(saleData) {
    const {
      orderId,
      customerId,
      totalAmount,
      metalCost,
      makingCharges,
      gstAmount,
      paymentMethod,
      date = new Date()
    } = saleData;

    // For cash sales: Debit Cash, Credit Jewelry Sales Revenue
    // For credit sales: Debit Accounts Receivable, Credit Jewelry Sales Revenue
    const debitAccount = paymentMethod === 'cash' ? 'MAIN-1001' : 'MAIN-1003'; // Cash or AR
    const creditAccount = 'MAIN-4001'; // Jewelry Sales Revenue

    return {
      transactionId: `SALE-${orderId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description: `Sale to customer - Order ${orderId}`,
      reference: `ORDER-${orderId}`,
      referenceType: 'sale',
      referenceId: orderId,
      lines: [
        {
          accountId: debitAccount,
          debit: totalAmount,
          credit: 0,
          description: paymentMethod === 'cash' ? 'Cash received from customer' : 'Amount due from customer'
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: totalAmount,
          description: 'Sales revenue from gold jewelry'
        }
      ],
      totalDebit: totalAmount,
      totalCredit: totalAmount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        customerId,
        metalCost,
        makingCharges,
        gstAmount,
        paymentMethod
      }
    };
  }

  /**
   * Create automated journal entry for purchase transaction
   * @param {Object} purchaseData - Purchase transaction data
   * @returns {Object} Journal entry data
   */
  createPurchaseEntry(purchaseData) {
    const {
      purchaseId,
      manufacturerId,
      totalAmount,
      metalCost,
      makingCharges,
      gstAmount,
      paymentMethod,
      date = new Date()
    } = purchaseData;

    // For cash purchases: Debit Metal Inventory, Credit Cash
    // For credit purchases: Debit Metal Inventory, Credit Accounts Payable
    const debitAccount = 'MAIN-1004'; // Gold Inventory (can be updated based on metal type)
    const creditAccount = paymentMethod === 'cash' ? 'MAIN-1001' : 'MAIN-2001'; // Cash or AP

    return {
      transactionId: `PURCHASE-${purchaseId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description: `Purchase from manufacturer - ${purchaseId}`,
      reference: `PURC-${purchaseId}`,
      referenceType: 'purchase',
      referenceId: purchaseId,
      lines: [
        {
          accountId: debitAccount,
          debit: totalAmount,
          credit: 0,
          description: 'Inventory purchased from manufacturer'
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: totalAmount,
          description: paymentMethod === 'cash' ? 'Cash paid to manufacturer' : 'Amount due to manufacturer'
        }
      ],
      totalDebit: totalAmount,
      totalCredit: totalAmount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        manufacturerId,
        metalCost,
        makingCharges,
        gstAmount,
        paymentMethod
      }
    };
  }

  /**
   * Create automated journal entry for payment received
   * @param {Object} paymentData - Payment transaction data
   * @returns {Object} Journal entry data
   */
  createPaymentReceivedEntry(paymentData) {
    const {
      paymentId,
      customerId,
      amount,
      paymentMethod,
      reference,
      date = new Date()
    } = paymentData;

    let debitAccount, creditAccount;

    if (paymentMethod === 'cash') {
      debitAccount = 'MAIN-1001'; // Cash
      creditAccount = 'MAIN-1003'; // Accounts Receivable
    } else {
      debitAccount = 'MAIN-1002'; // Bank Account
      creditAccount = 'MAIN-1003'; // Accounts Receivable
    }

    return {
      transactionId: `PAYMENT-RCV-${paymentId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description: `Payment received from customer - ${reference}`,
      reference: `PAY-${paymentId}`,
      referenceType: 'payment_received',
      referenceId: paymentId,
      lines: [
        {
          accountId: debitAccount,
          debit: amount,
          credit: 0,
          description: `${paymentMethod} payment received`
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: amount,
          description: 'Reduction in accounts receivable'
        }
      ],
      totalDebit: amount,
      totalCredit: amount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        customerId,
        paymentMethod,
        reference
      }
    };
  }

  /**
   * Create automated journal entry for payment made
   * @param {Object} paymentData - Payment transaction data
   * @returns {Object} Journal entry data
   */
  createPaymentMadeEntry(paymentData) {
    const {
      paymentId,
      manufacturerId,
      amount,
      paymentMethod,
      reference,
      date = new Date()
    } = paymentData;

    let debitAccount, creditAccount;

    debitAccount = 'MAIN-2001'; // Accounts Payable
    if (paymentMethod === 'cash') {
      creditAccount = 'MAIN-1001'; // Cash
    } else {
      creditAccount = 'MAIN-1002'; // Bank Account
    }

    return {
      transactionId: `PAYMENT-PAID-${paymentId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description: `Payment made to manufacturer - ${reference}`,
      reference: `PAY-${paymentId}`,
      referenceType: 'payment_made',
      referenceId: paymentId,
      lines: [
        {
          accountId: debitAccount,
          debit: amount,
          credit: 0,
          description: 'Reduction in accounts payable'
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: amount,
          description: `${paymentMethod} payment made`
        }
      ],
      totalDebit: amount,
      totalCredit: amount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        manufacturerId,
        paymentMethod,
        reference
      }
    };
  }

  /**
   * Create automated journal entry for inventory adjustment
   * @param {Object} adjustmentData - Inventory adjustment data
   * @returns {Object} Journal entry data
   */
  createInventoryAdjustmentEntry(adjustmentData) {
    const {
      adjustmentId,
      productId,
      quantity,
      unitCost,
      adjustmentType, // 'increase' or 'decrease'
      reason,
      date = new Date()
    } = adjustmentData;

    const totalValue = quantity * unitCost;
    let debitAccount, creditAccount, description;

    if (adjustmentType === 'increase') {
      debitAccount = 'MAIN-1004'; // Gold Inventory
      creditAccount = 'MAIN-4003'; // Other Income (inventory gain)
      description = `Metal inventory increase - ${reason}`;
    } else {
      debitAccount = 'MAIN-5107'; // Wastage Loss
      creditAccount = 'MAIN-1004'; // Gold Inventory
      description = `Metal inventory decrease/wastage - ${reason}`;
    }

    return {
      transactionId: `INV-ADJ-${adjustmentId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description,
      reference: `ADJ-${adjustmentId}`,
      referenceType: 'inventory_adjustment',
      referenceId: adjustmentId,
      lines: [
        {
          accountId: debitAccount,
          debit: totalValue,
          credit: 0,
          description: `${adjustmentType} in inventory value`
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: totalValue,
          description: `Adjustment for inventory ${adjustmentType}`
        }
      ],
      totalDebit: totalValue,
      totalCredit: totalValue,
      balanced: true,
      autoGenerated: true,
      metadata: {
        productId,
        quantity,
        unitCost,
        adjustmentType,
        reason
      }
    };
  }

  /**
   * Create automated journal entry for GST transactions
   * @param {Object} gstData - GST transaction data
   * @returns {Object} Journal entry data
   */
  createGSTEntry(gstData) {
    const {
      transactionId,
      gstAmount,
      gstType, // 'input' or 'output'
      reference,
      date = new Date()
    } = gstData;

    let debitAccount, creditAccount, description;

    if (gstType === 'output') {
      // GST collected from customers
      debitAccount = 'MAIN-2002'; // GST Payable
      creditAccount = 'MAIN-4001'; // Sales Revenue (GST portion)
      description = `GST collected on sales - ${reference}`;
    } else {
      // GST paid to suppliers
      debitAccount = 'MAIN-1006'; // GST Input Tax Credit
      creditAccount = 'MAIN-2001'; // Accounts Payable (GST portion)
      description = `GST input tax credit - ${reference}`;
    }

    return {
      transactionId: `GST-${gstType.toUpperCase()}-${transactionId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description,
      reference: `GST-${reference}`,
      referenceType: 'gst',
      referenceId: transactionId,
      lines: [
        {
          accountId: debitAccount,
          debit: gstAmount,
          credit: 0,
          description: `${gstType} GST amount`
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: gstAmount,
          description: `GST ${gstType} adjustment`
        }
      ],
      totalDebit: gstAmount,
      totalCredit: gstAmount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        gstType,
        gstAmount,
        reference
      }
    };
  }

  /**
   * Create automated journal entry for commission payments
   * @param {Object} commissionData - Commission payment data
   * @returns {Object} Journal entry data
   */
  createCommissionEntry(commissionData) {
    const {
      commissionId,
      vanSellerId,
      amount,
      paymentMethod,
      period,
      date = new Date()
    } = commissionData;

    const debitAccount = 'MAIN-5101'; // Salaries & Wages
    const creditAccount = paymentMethod === 'cash' ? 'MAIN-1001' : 'MAIN-1002'; // Cash or Bank

    return {
      transactionId: `COMM-${commissionId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description: `Commission payment to van seller - ${period}`,
      reference: `COMM-${commissionId}`,
      referenceType: 'commission',
      referenceId: commissionId,
      lines: [
        {
          accountId: debitAccount,
          debit: amount,
          credit: 0,
          description: 'Commission expense'
        },
        {
          accountId: creditAccount,
          debit: 0,
          credit: amount,
          description: `${paymentMethod} payment for commission`
        }
      ],
      totalDebit: amount,
      totalCredit: amount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        vanSellerId,
        paymentMethod,
        period
      }
    };
  }

  /**
   * Create automated journal entry for jewelry sale with making charges
   * @param {Object} jewelrySaleData - Jewelry sale transaction data
   * @returns {Object} Journal entry data
   */
  createJewelrySaleEntry(jewelrySaleData) {
    const {
      orderId,
      customerId,
      metalCost,
      makingCharges,
      gstAmount,
      totalAmount,
      paymentMethod,
      date = new Date()
    } = jewelrySaleData;

    // For cash sales: Debit Cash, Credit Sales Revenue + Making Charges + GST
    // For credit sales: Debit Accounts Receivable, Credit Sales Revenue + Making Charges + GST
    const debitAccount = paymentMethod === 'cash' ? 'MAIN-1001' : 'MAIN-1003'; // Cash or AR

    return {
      transactionId: `JEWELRY-SALE-${orderId}-${Date.now()}`,
      companyId: this.companyId,
      date,
      description: `Jewelry sale to customer - Order ${orderId}`,
      reference: `ORDER-${orderId}`,
      referenceType: 'jewelry_sale',
      referenceId: orderId,
      lines: [
        {
          accountId: debitAccount,
          debit: totalAmount,
          credit: 0,
          description: paymentMethod === 'cash' ? 'Cash received from customer' : 'Amount due from customer'
        },
        {
          accountId: 'MAIN-4001', // Jewelry Sales Revenue (metal cost)
          debit: 0,
          credit: metalCost,
          description: 'Revenue from metal sales'
        },
        {
          accountId: 'MAIN-4002', // Making Charges Income
          debit: 0,
          credit: makingCharges,
          description: 'Making charges income'
        },
        {
          accountId: 'MAIN-2002', // GST Payable
          debit: 0,
          credit: gstAmount,
          description: 'GST collected on sale'
        }
      ],
      totalDebit: totalAmount,
      totalCredit: totalAmount,
      balanced: true,
      autoGenerated: true,
      metadata: {
        customerId,
        metalCost,
        makingCharges,
        gstAmount,
        paymentMethod
      }
    };
  }
}